/* eslint-disable */
/**
 * GENERATED by apps/web/scripts/generate-qr-logo-emoji.mjs — do not edit by hand.
 *
 * Emoji artwork from Twemoji 17.0.3 (https://github.com/jdecked/twemoji),
 * Copyright 2019 Twitter, Inc and other contributors.
 * Graphics licensed under CC-BY 4.0: https://creativecommons.org/licenses/by/4.0/
 * Only a width/height was added to each file's root element; the artwork is unchanged.
 */

export type QrLogoEmoji = {
  /** Twemoji file name: lowercase code points joined by `-`. */
  code: string;
  char: string;
  en: string;
  tr: string;
  keywords: string;
};

export const TWEMOJI_VERSION = "17.0.3";

export const QR_LOGO_EMOJI: readonly QrLogoEmoji[] = [
  {"code":"1f600","char":"😀","en":"Grinning face","tr":"Sırıtan yüz","keywords":"smile happy gülen mutlu"},
  {"code":"1f602","char":"😂","en":"Tears of joy","tr":"Sevinç gözyaşları","keywords":"laugh lol kahkaha gülmek"},
  {"code":"1f60d","char":"😍","en":"Heart eyes","tr":"Kalp gözler","keywords":"love aşk sevgi"},
  {"code":"1f60e","char":"😎","en":"Sunglasses","tr":"Güneş gözlüklü","keywords":"cool havalı"},
  {"code":"1f609","char":"😉","en":"Winking face","tr":"Göz kırpan","keywords":"wink göz kırpma"},
  {"code":"1f929","char":"🤩","en":"Star-struck","tr":"Hayran","keywords":"wow star yıldız"},
  {"code":"1f973","char":"🥳","en":"Partying face","tr":"Parti yüzü","keywords":"party celebrate kutlama"},
  {"code":"1f914","char":"🤔","en":"Thinking face","tr":"Düşünen yüz","keywords":"hmm question soru"},
  {"code":"1f44d","char":"👍","en":"Thumbs up","tr":"Beğeni","keywords":"like ok onay"},
  {"code":"1f44f","char":"👏","en":"Clapping hands","tr":"Alkış","keywords":"applause bravo"},
  {"code":"1f64c","char":"🙌","en":"Raising hands","tr":"Eller havada","keywords":"hooray yaşasın"},
  {"code":"1f64f","char":"🙏","en":"Folded hands","tr":"Teşekkür","keywords":"thanks please rica dua"},
  {"code":"1f44b","char":"👋","en":"Waving hand","tr":"El sallama","keywords":"hello hi merhaba selam"},
  {"code":"270c","char":"✌","en":"Victory hand","tr":"Zafer işareti","keywords":"peace barış"},
  {"code":"1f4aa","char":"💪","en":"Flexed biceps","tr":"Pazı","keywords":"strong gym güçlü spor"},
  {"code":"2764","char":"❤","en":"Red heart","tr":"Kırmızı kalp","keywords":"love aşk sevgi"},
  {"code":"1f525","char":"🔥","en":"Fire","tr":"Ateş","keywords":"hot lit sıcak"},
  {"code":"2728","char":"✨","en":"Sparkles","tr":"Parıltı","keywords":"new magic yeni sihir"},
  {"code":"2b50","char":"⭐","en":"Star","tr":"Yıldız","keywords":"favourite favori"},
  {"code":"1f4af","char":"💯","en":"Hundred points","tr":"Yüz puan","keywords":"perfect score mükemmel"},
  {"code":"1f389","char":"🎉","en":"Party popper","tr":"Konfeti","keywords":"celebrate tada kutlama"},
  {"code":"1f381","char":"🎁","en":"Gift","tr":"Hediye","keywords":"present sürpriz"},
  {"code":"1f382","char":"🎂","en":"Birthday cake","tr":"Doğum günü pastası","keywords":"birthday doğum günü"},
  {"code":"1f388","char":"🎈","en":"Balloon","tr":"Balon","keywords":"party parti"},
  {"code":"1f451","char":"👑","en":"Crown","tr":"Taç","keywords":"king queen vip kral"},
  {"code":"1f48e","char":"💎","en":"Gem","tr":"Mücevher","keywords":"diamond elmas"},
  {"code":"1f3c6","char":"🏆","en":"Trophy","tr":"Kupa","keywords":"winner award ödül"},
  {"code":"1f680","char":"🚀","en":"Rocket","tr":"Roket","keywords":"launch startup başlat"},
  {"code":"1f4a1","char":"💡","en":"Light bulb","tr":"Ampul","keywords":"idea fikir"},
  {"code":"1f514","char":"🔔","en":"Bell","tr":"Zil","keywords":"notification bildirim"},
  {"code":"2705","char":"✅","en":"Check mark","tr":"Onay işareti","keywords":"done ok tamam"},
  {"code":"1f4cd","char":"📍","en":"Round pushpin","tr":"Konum iğnesi","keywords":"location map harita konum"},
  {"code":"1f3e0","char":"🏠","en":"House","tr":"Ev","keywords":"home"},
  {"code":"1f6cd","char":"🛍","en":"Shopping bags","tr":"Alışveriş poşetleri","keywords":"shop store mağaza"},
  {"code":"1f6d2","char":"🛒","en":"Shopping cart","tr":"Alışveriş sepeti","keywords":"cart shop sepet"},
  {"code":"1f4b0","char":"💰","en":"Money bag","tr":"Para kesesi","keywords":"money sale para indirim"},
  {"code":"1f4f7","char":"📷","en":"Camera","tr":"Kamera","keywords":"photo fotoğraf"},
  {"code":"1f3b5","char":"🎵","en":"Musical note","tr":"Müzik notası","keywords":"music song şarkı"},
  {"code":"2615","char":"☕","en":"Hot beverage","tr":"Sıcak içecek","keywords":"coffee tea kahve çay"},
  {"code":"1f355","char":"🍕","en":"Pizza","tr":"Pizza","keywords":"food menu yemek"},
  {"code":"1f354","char":"🍔","en":"Hamburger","tr":"Hamburger","keywords":"burger food yemek"},
  {"code":"1f377","char":"🍷","en":"Wine glass","tr":"Şarap kadehi","keywords":"wine drink içki"},
  {"code":"1f33b","char":"🌻","en":"Sunflower","tr":"Ayçiçeği","keywords":"flower çiçek"},
  {"code":"1f308","char":"🌈","en":"Rainbow","tr":"Gökkuşağı","keywords":"pride colour renk"},
  {"code":"1f436","char":"🐶","en":"Dog face","tr":"Köpek","keywords":"dog pet evcil"},
  {"code":"1f431","char":"🐱","en":"Cat face","tr":"Kedi","keywords":"cat pet evcil"},
  {"code":"26bd","char":"⚽","en":"Soccer ball","tr":"Futbol topu","keywords":"football sport spor"},
  {"code":"1f1f9-1f1f7","char":"🇹🇷","en":"Flag: Türkiye","tr":"Türkiye bayrağı","keywords":"turkey turkiye tr bayrak"},
];
