import { Icon } from "@/components/kit/icon";
import Link from "next/link";
import { getTranslations } from "next-intl/server";
import { Button } from "@/components/ui";
import { formatDate } from "@/lib/format";
import { getLatestQrCodeForLink, qrPayload } from "@/lib/qr-codes";
import { buildQrSvg } from "@/lib/qr-svg";
import { LinkQrButton } from "./link-qr-button";

type LinkQrCardProps = {
  workspaceId: string;
  linkId: string;
};

/**
 * "QR code" panel on the link editor: the newest code that encodes this link with a
 * shortcut into the designer, or a one-click create when there is none yet.
 */
export async function LinkQrCard({ workspaceId, linkId }: LinkQrCardProps) {
  const [t, { latest, total }] = await Promise.all([
    getTranslations("qr"),
    getLatestQrCodeForLink(workspaceId, linkId),
  ]);

  // Preview only: the browser loads the logo, exports inline it server-side.
  const svg = latest
    ? buildQrSvg(qrPayload(latest), latest.style, { logoHref: latest.style.logoUrl, size: 160 })
    : null;

  return (
    <section
      aria-labelledby="link-qr-title"
      className="flex min-w-0 flex-col gap-4 rounded-default border border-border bg-bg p-5 sm:flex-row sm:items-center"
    >
      {latest && svg ? (
        <Link
          href={`/qr/${latest.id}`}
          aria-label={t("editNamed", { name: latest.name })}
          className="flex size-28 shrink-0 items-center justify-center self-center overflow-hidden rounded-default border border-border bg-surface-subtle p-2 no-underline sm:self-auto [&>svg]:h-auto [&>svg]:w-full"
          // Generated by buildQrSvg; caption and logo URL are XML-escaped.
          dangerouslySetInnerHTML={{ __html: svg }}
        />
      ) : (
        <span
          aria-hidden="true"
          className="flex size-28 shrink-0 items-center justify-center self-center rounded-default border border-dashed border-border-strong bg-surface-subtle text-fg-disabled sm:self-auto"
        >
          <Icon name="qrcode" className="text-3xl" />
        </span>
      )}

      <div className="flex min-w-0 flex-1 flex-col gap-3">
        <div className="flex min-w-0 flex-col gap-1">
          <span className="font-mono text-xs tracking-widest text-fg-subtle uppercase">
            {t("linkCard.eyebrow")}
          </span>
          <h2 id="link-qr-title" className="m-0 truncate text-base font-semibold">
            {latest ? latest.name : t("linkCard.emptyTitle")}
          </h2>
          <p className="m-0 text-sm text-fg-muted">
            {latest
              ? t("created", { date: formatDate(latest.createdAt) })
              : t("linkCard.emptyDesc")}
          </p>
          {total > 1 ? (
            <p className="m-0 text-xs text-fg-subtle">
              {t("linkCard.moreCodes", { count: total })}{" "}
              <Link href={`/qr?linkId=${linkId}`} className="font-medium">
                {t("linkCard.viewAll")}
              </Link>
            </p>
          ) : null}
        </div>

        {latest ? (
          <div className="flex min-w-0 flex-wrap items-center gap-2">
            <Button size="sm" variant="primary" href={`/qr/${latest.id}`}>
              <Icon name="pen" className="text-sm" aria-hidden="true" />
              {t("linkCard.edit")}
            </Button>
            <Button size="sm" href={`/api/qr/${latest.id}?format=png`}>
              <Icon name="download" className="text-sm" aria-hidden="true" />
              PNG
            </Button>
            <Button size="sm" variant="ghost" href={`/qr/new?linkId=${linkId}`}>
              <Icon name="plus" className="text-sm" aria-hidden="true" />
              {t("linkCard.another")}
            </Button>
          </div>
        ) : (
          <LinkQrButton linkId={linkId} />
        )}
      </div>
    </section>
  );
}
