import { Icon } from "@/components/kit/icon";
import Link from "next/link";
import { getLocale, getTranslations } from "next-intl/server";
import { Button, Card } from "@/components/ui";
import { formatDate } from "@/lib/format";
import { getLatestQrCodeForLink, qrPayload } from "@/lib/qr-codes";
import { buildQrSvg } from "@/lib/qr-svg";
import { LinkQrButton } from "./link-qr-button";

type LinkQrCardProps = {
  workspaceId: string;
  linkId: string;
};

/**
 * "QR code" card beside the link editor: the newest code that encodes this link with a
 * shortcut into the designer, or a one-click create when there is none yet.
 */
export async function LinkQrCard({ workspaceId, linkId }: LinkQrCardProps) {
  const locale = await getLocale();
  const [t, { latest, total }] = await Promise.all([
    getTranslations("qr"),
    getLatestQrCodeForLink(workspaceId, linkId),
  ]);

  // Preview only: the browser loads the logo, exports inline it server-side.
  const svg = latest
    ? buildQrSvg(qrPayload(latest), latest.style, { logoHref: latest.style.logoUrl, size: 160 })
    : null;

  return (
    <Card
      title={
        <span className="flex items-center gap-2">
          <Icon name="qrcode" className="text-xs text-fg-subtle" />
          {t("linkCard.eyebrow")}
        </span>
      }
      description={latest ? latest.name : t("linkCard.emptyTitle")}
      actions={
        total > 1 ? (
          <Button size="sm" variant="ghost" trailingIcon="arrow-right" href={`/qr?linkId=${linkId}`}>
            {t("linkCard.viewAll")}
          </Button>
        ) : null
      }
    >
      <div className="flex min-w-0 items-start gap-4">
        {latest && svg ? (
          <Link
            href={`/qr/${latest.id}`}
            aria-label={t("editNamed", { name: latest.name })}
            className="flex size-24 shrink-0 items-center justify-center overflow-hidden rounded-md border border-border bg-surface-subtle p-1.5 no-underline transition-colors hover:border-border-strong [&>svg]:h-auto [&>svg]:w-full"
            // Generated by buildQrSvg; caption and logo URL are XML-escaped.
            dangerouslySetInnerHTML={{ __html: svg }}
          />
        ) : (
          <span
            aria-hidden="true"
            className="flex size-24 shrink-0 items-center justify-center rounded-md border border-dashed border-border-strong bg-surface-subtle text-fg-disabled"
          >
            <Icon name="qrcode" className="text-2xl" />
          </span>
        )}

        <div className="flex min-w-0 flex-1 flex-col gap-2">
          <p className="m-0 text-[13px] leading-5 text-fg-muted">
            {latest ? t("created", { date: formatDate(latest.createdAt, locale) }) : t("linkCard.emptyDesc")}
          </p>
          {total > 1 ? (
            <p className="m-0 text-xs text-fg-subtle">{t("linkCard.moreCodes", { count: total })}</p>
          ) : null}
          {latest ? (
            <div className="flex min-w-0 flex-wrap items-center gap-2">
              <Button size="sm" leadingIcon="pen" href={`/qr/${latest.id}`}>
                {t("linkCard.edit")}
              </Button>
              {/* `download` keeps this a plain anchor: an API route must not go through client navigation. */}
              <Button size="sm" variant="ghost" leadingIcon="download" href={`/api/qr/${latest.id}?format=png`} download="qr-code.png">
                PNG
              </Button>
            </div>
          ) : null}
        </div>
      </div>

      {latest ? (
        <Button size="sm" variant="ghost" leadingIcon="plus" className="w-fit" href={`/qr/new?linkId=${linkId}`}>
          {t("linkCard.another")}
        </Button>
      ) : (
        <LinkQrButton linkId={linkId} />
      )}
    </Card>
  );
}
