import type { Metadata } from "next";
import { Download, MoreHorizontal, Plus, QrCode } from "lucide-react";
import Link from "next/link";
import { PanelShell } from "@/components/shell/panel-shell";
import { QueryPagination } from "@/components/shell/query-pagination";
import { Badge, Button, Card, Dropdown, EmptyState, Grid, Hero } from "@/components/ui";
import { formatDate } from "@/lib/format";
import { listQrCodes, qrPayload } from "@/lib/qr-codes";
import { buildQrSvg } from "@/lib/qr-svg";
import { requireWorkspace } from "@/lib/session";

export const metadata: Metadata = { title: "QR codes" };

const PAGE_SIZE = 12;

type SearchParams = Promise<Record<string, string | string[] | undefined>>;

export default async function QrListPage({ searchParams }: { searchParams: SearchParams }) {
  const context = await requireWorkspace();
  const raw = await searchParams;
  const pageParam = Number(Array.isArray(raw.page) ? raw.page[0] : raw.page);
  const page = Number.isFinite(pageParam) && pageParam > 0 ? Math.floor(pageParam) : 1;

  const { items, total } = await listQrCodes(context.workspace.id, page, PAGE_SIZE);

  return (
    <PanelShell
      title="QR codes"
      crumbs={[{ label: context.workspace.name }]}
      topbarActions={
        <Button variant="primary" href="/qr/new">
          <Plus className="size-4" />
          New QR code
        </Button>
      }
    >
      {items.length === 0 ? (
        <EmptyState
          icon={<QrCode className="size-5" />}
          eyebrow="QR codes"
          title="No QR codes yet"
          description="Design a code once, print it, and re-target it later by editing the short link behind it."
          actions={
            <Button variant="primary" href="/qr/new">
              Design a QR code
            </Button>
          }
        />
      ) : (
        <>
          <Hero
            variant="compact"
            eyebrow={`${total} ${total === 1 ? "code" : "codes"}`}
            title="QR codes"
            description="Every code encodes a short link, so a printed poster can be pointed somewhere new without reprinting."
          />

          <Grid columns={4}>
            {items.map((item) => {
              // Preview only: the browser loads the logo, exports inline it server-side.
              const svg = buildQrSvg(qrPayload(item), item.style, {
                logoHref: item.style.logoUrl,
                size: 240,
              });

              return (
                <Card key={item.id} className="gap-3.5">
                  <Link
                    href={`/qr/${item.id}`}
                    aria-label={`Edit ${item.name}`}
                    className="flex items-center justify-center overflow-hidden rounded-default border border-border bg-surface-subtle p-3 no-underline [&>svg]:h-auto [&>svg]:w-full [&>svg]:rounded-sm"
                    // Generated by buildQrSvg; caption and logo URL are XML-escaped.
                    dangerouslySetInnerHTML={{ __html: svg }}
                  />

                  <div className="flex min-w-0 flex-col gap-1">
                    <Link
                      href={`/qr/${item.id}`}
                      className="truncate text-sm font-medium text-ink no-underline hover:underline"
                    >
                      {item.name}
                    </Link>
                    <span className="truncate font-mono text-xs text-fg-muted">
                      {item.hostname}/{item.slug}
                    </span>
                    <span className="font-mono text-xs text-fg-disabled tabular-nums">
                      Created {formatDate(item.createdAt)}
                    </span>
                  </div>

                  <div className="flex min-w-0 flex-wrap items-center justify-between gap-2">
                    {item.linkArchived ? (
                      <Badge tone="warn">Link archived</Badge>
                    ) : (
                      <Badge tone="muted">Active</Badge>
                    )}
                    <span className="flex shrink-0 items-center gap-1">
                      <Button size="sm" variant="ghost" href={`/api/qr/${item.id}?format=png`}>
                        <Download className="size-4" aria-hidden="true" />
                        PNG
                      </Button>
                      <Dropdown
                        trigger={
                          <Button
                            size="sm"
                            variant="ghost"
                            icon
                            aria-label={`More export formats for ${item.name}`}
                          >
                            <MoreHorizontal className="size-4" />
                          </Button>
                        }
                        items={[
                          {
                            id: "svg",
                            label: "Download SVG",
                            href: `/api/qr/${item.id}?format=svg`,
                          },
                          {
                            id: "pdf",
                            label: "Download PDF",
                            href: `/api/qr/${item.id}?format=pdf`,
                          },
                          {
                            id: "edit",
                            label: "Edit design",
                            href: `/qr/${item.id}`,
                            separated: true,
                          },
                        ]}
                      />
                    </span>
                  </div>
                </Card>
              );
            })}
          </Grid>

          <QueryPagination page={page} pageSize={PAGE_SIZE} total={total} />
        </>
      )}
    </PanelShell>
  );
}
