import { cn } from "@/lib/cx";
import { config } from "@fortawesome/fontawesome-svg-core";
import {
  faAndroid,
  faApple,
  faChrome,
  faCloudflare,
  faEdge,
  faFacebook,
  faFirefoxBrowser,
  faGithub,
  faGoogle,
  faInstagram,
  faLinkedin,
  faLinux,
  faSafari,
  faSlack,
  faTelegram,
  faTiktok,
  faWhatsapp,
  faWindows,
  faXTwitter,
  faYoutube,
} from "@fortawesome/free-brands-svg-icons";
import {
  faAddressCard,
  faArrowDown,
  faArrowLeft,
  faArrowPointer,
  faArrowRight,
  faArrowTrendUp,
  faArrowUp,
  faArrowUpRightFromSquare,
  faAt,
  faBan,
  faBars,
  faBolt,
  faBook,
  faBoxArchive,
  faBoxOpen,
  faBuilding,
  faBullseye,
  faCalendarDays,
  faChartLine,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleCheck,
  faCircleInfo,
  faCircleXmark,
  faClock,
  faCloudArrowUp,
  faCode,
  faCompass,
  faCopy,
  faCreditCard,
  faDesktop,
  faDownload,
  faEarthEurope,
  faEllipsis,
  faEnvelope,
  faEnvelopeCircleCheck,
  faEye,
  faEyeSlash,
  faFileCode,
  faFileExport,
  faFileImage,
  faFileLines,
  faFilter,
  faFlag,
  faFolder,
  faGaugeHigh,
  faGear,
  faGlobe,
  faGripVertical,
  faHeartPulse,
  faInbox,
  faKey,
  faLaptop,
  faLayerGroup,
  faLink,
  faLock,
  faMagnifyingGlass,
  faMinus,
  faMobileScreen,
  faMoon,
  faPalette,
  faPen,
  faPlus,
  faQrcode,
  faRepeat,
  faRightFromBracket,
  faRotateRight,
  faScroll,
  faShareNodes,
  faShieldHalved,
  faSliders,
  faSort,
  faSpinner,
  faSun,
  faTabletScreenButton,
  faTag,
  faTerminal,
  faTrash,
  faTriangleExclamation,
  faUnlock,
  faUserCheck,
  faUserGear,
  faUserPlus,
  faUsers,
  faWandMagicSparkles,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";

config.autoAddCss = false;

/**
 * Theme icon pack (Font Awesome 6 SVG, same glyphs as /docs catalog).
 * UI names match `copy.json` uiIcons; brand names match brandIcons.
 */
export const ICONS = {
  folder: faFolder,
  export: faFileExport,
  "chart-line": faChartLine,
  globe: faGlobe,
  copy: faCopy,
  plus: faPlus,
  gear: faGear,
  "gauge-high": faGaugeHigh,
  "cloud-up": faCloudArrowUp,
  "arrow-down": faArrowDown,
  "arrow-up": faArrowUp,
  "arrow-trend-up": faArrowTrendUp,
  "arrow-right": faArrowRight,
  "arrow-left": faArrowLeft,
  search: faMagnifyingGlass,
  filter: faFilter,
  calendar: faCalendarDays,
  clock: faClock,
  tag: faTag,
  "user-plus": faUserPlus,
  "user-check": faUserCheck,
  "user-gear": faUserGear,
  users: faUsers,
  code: faCode,
  key: faKey,
  shield: faShieldHalved,
  trash: faTrash,
  pen: faPen,
  ellipsis: faEllipsis,
  check: faCheck,
  "circle-check": faCircleCheck,
  "circle-xmark": faCircleXmark,
  xmark: faXmark,
  "circle-info": faCircleInfo,
  warning: faTriangleExclamation,
  "chevron-down": faChevronDown,
  "chevron-up": faChevronUp,
  "chevron-left": faChevronLeft,
  "chevron-right": faChevronRight,
  "layer-group": faLayerGroup,
  bolt: faBolt,
  earth: faEarthEurope,
  link: faLink,
  qrcode: faQrcode,
  "address-card": faAddressCard,
  bullseye: faBullseye,
  book: faBook,
  building: faBuilding,
  "credit-card": faCreditCard,
  palette: faPalette,
  pulse: faHeartPulse,
  scroll: faScroll,
  "right-from-bracket": faRightFromBracket,
  sort: faSort,
  spinner: faSpinner,
  sun: faSun,
  moon: faMoon,
  lock: faLock,
  unlock: faUnlock,
  eye: faEye,
  "eye-slash": faEyeSlash,
  envelope: faEnvelope,
  "envelope-circle-check": faEnvelopeCircleCheck,
  inbox: faInbox,
  compass: faCompass,
  "rotate-right": faRotateRight,
  download: faDownload,
  "external-link": faArrowUpRightFromSquare,
  sliders: faSliders,
  terminal: faTerminal,
  flag: faFlag,
  ban: faBan,
  bars: faBars,
  laptop: faLaptop,
  "share-nodes": faShareNodes,
  "arrow-pointer": faArrowPointer,
  repeat: faRepeat,
  minus: faMinus,
  sparkles: faWandMagicSparkles,
  "mobile-screen": faMobileScreen,
  desktop: faDesktop,
  tablet: faTabletScreenButton,
  grip: faGripVertical,
  archive: faBoxArchive,
  "archive-restore": faBoxOpen,
  image: faFileImage,
  "file-lines": faFileLines,
  "file-code": faFileCode,
  at: faAt,
  apple: faApple,
  android: faAndroid,
  windows: faWindows,
  linux: faLinux,
  chrome: faChrome,
  safari: faSafari,
  firefox: faFirefoxBrowser,
  edge: faEdge,
  linkedin: faLinkedin,
  "x-twitter": faXTwitter,
  instagram: faInstagram,
  whatsapp: faWhatsapp,
  youtube: faYoutube,
  github: faGithub,
  google: faGoogle,
  cloudflare: faCloudflare,
  slack: faSlack,
  tiktok: faTiktok,
  facebook: faFacebook,
  telegram: faTelegram,
} as const satisfies Record<string, IconDefinition>;

export type IconName = keyof typeof ICONS;

type IconProps = {
  name: IconName;
  className?: string;
};

export function Icon({ name, className }: IconProps) {
  return (
    <FontAwesomeIcon
      icon={ICONS[name]}
      className={cn("kit-icon", className)}
      spin={name === "spinner"}
      aria-hidden
    />
  );
}
